logging:
  level:
    #ROOT: INFO
    #tech.jhipster: INFO
    #com.mycompany.iaeval: INFO
    org.springframework.web.client: DEBUG
    org.springframework.ai: DEBUG

server:
  port: 8080
  shutdown: graceful

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://iaeval-postgresql:5432/iaeval
    username: iaeval
    password: iaeval
    hikari:
      poolName: Hikari
      auto-commit: false

  security:
    oauth2:
      client:
        provider:
          keycloak:
            # URL interne pour la validation des tokens entre containers
            issuer-uri: http://iaeval-keycloak:9080/realms/jhipster
        registration:
          oidc: # On utilise 'oidc' comme ID d'enregistrement par défaut JHipster
            client-id: web_app
            client-secret: web_app
            scope: openid,profile,email

  liquibase:
    contexts: prod

  ai:
    mistralai:
      api-key: ${SPRING_AI_MISTRALAI_API_KEY}
      chat:
        options:
          model: mistral-small-latest # Ou mistral-large-latest si besoin
          temperature: 0.7
          max-tokens: 1000
      base-url: https://api.mistral.ai
    vectorstore:
      qdrant:
        host: iaeval-qdrant
        port: 6334
        initialize-schema: true

# 6. CONFIGURATION MIDDLEWARE (API EXTERNE)
external-api:
  base-url: ${EXTERNAL_API_BASE_URL:http://plateforme-metier.com/api}
  endpoints:
    appels-offres: /appels-offres
    soumissionnaires: /appels-offres/{id}/soumissionnaires
    documents: /candidats/{id}/documents
