name: iaeval
services:
  iaeval-app:
    image: iaeval
    container_name: iaeval-app
    # FORÇAGE DE L'ATTENTE : On attend 60s RÉELLES avant de lancer Java
    entrypoint:
      [
        'sh',
        '-c',
        "until curl -s http://iaeval-keycloak:9080/realms/jhipster; do echo 'En attente de Keycloak...'; sleep 5; done; java -cp @/app/jib-classpath-file com.mycompany.iaeval.IaevalApp",
      ]
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m -Djackson.maxStringLength=20000000
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      # Traces ReferenceLegale / Tika / REST (docker logs -f iaeval-app)
      - LOGGING_LEVEL_COM_MYCOMPANY_IAEVAL=INFO
      - SPRING_DATASOURCE_URL=jdbc:postgresql://iaeval-postgresql:5432/iaeval
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://iaeval-postgresql:5432/iaeval

      # --- SÉCURITÉ (Utilisation du nom de service Docker) ---
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://iaeval-keycloak:9080/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=web_app
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=web_app

      # --- IA CONFIGURATION ---
      - SPRING_AI_MISTRALAI_API_KEY=${SPRING_AI_MISTRALAI_API_KEY}
      - SPRING_AI_VECTORSTORE_QDRANT_HOST=iaeval-qdrant
      - SPRING_AI_VECTORSTORE_QDRANT_PORT=6334
      - SPRING_AI_MISTRALAI_CHAT_OPTIONS_MODEL=mistral-small-latest
      - SPRING_AI_MISTRALAI_CHAT_OPTIONS_READ_TIMEOUT=120000
      - SPRING_JACKSON_GENERATOR_WRITE_NUMBERS_AS_STRINGS=true

    ports:
      - '8080:8080'
    networks:
      - iaeval-net
    depends_on:
      iaeval-postgresql:
        condition: service_healthy
      iaeval-keycloak:
        condition: service_started # On ne bloque plus sur healthy, on gère l'attente via sleep

  iaeval-postgresql:
    extends:
      file: ./postgresql.yml
      service: postgresql
    networks:
      - iaeval-net

  iaeval-keycloak:
    extends:
      file: ./keycloak.yml
      service: keycloak
    depends_on:
      iaeval-postgresql:
        condition: service_healthy
    networks:
      - iaeval-net

  iaeval-qdrant:
    image: qdrant/qdrant:latest
    container_name: iaeval-qdrant
    ports:
      - '6333:6333'
      - '6334:6334'
    volumes:
      - ./qdrant_storage:/qdrant/storage
    networks:
      - iaeval-net

# RÉSEAU UNIQUE POUR TOUT LE MONDE
networks:
  iaeval-net:
    driver: bridge
