services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.3
    container_name: iaeval-keycloak
    command: 'start-dev --import-realm'
    volumes:
      - ./realm-config:/opt/keycloak/data/import
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://iaeval-postgresql:5432/iaeval
      - KC_DB_USERNAME=iaeval
      - KC_DB_PASSWORD=iaeval
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HTTP_PORT=9080
      - KC_HOSTNAME_STRICT=false
      - KC_HEALTH_ENABLED=true
    # Le healthcheck vérifie si Keycloak répond sur son port
    healthcheck:
      test: ['CMD-SHELL', 'exec 3<>/dev/tcp/127.0.0.1/9080 && exit 0 || exit 1']
      interval: 5s
      timeout: 5s
      retries: 20 # Il va essayer pendant 100 secondes (20 * 5s)
    ports:
      - '9080:9080'
