services:
  postgresql: # Nom interne
    container_name: iaeval-postgresql
    image: postgres:17.2
    environment:
      - POSTGRES_USER=iaeval
      - POSTGRES_PASSWORD=iaeval
      - POSTGRES_DB=iaeval
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U iaeval']
      interval: 10s
      timeout: 5s
      retries: 5
